/* SarkariJobs+ — States & Categories Data */

const STATES = {
  AP: { name: "Andhra Pradesh",     slug: "andhra-pradesh",      psc: "APPSC",
        desc: "From Amaravati's secretariat to port city Visakhapatnam — APPSC Group-I/II, DSC teaching, police constable and SI recruitments draw lakhs of aspirants every cycle." },
  AR: { name: "Arunachal Pradesh",  slug: "arunachal-pradesh",   psc: "APPSC (Arunachal)",
        desc: "India's land of the dawn-lit mountains runs its own combined competitive services exam along with APPSCCE for civil services and departmental posts across Itanagar and district administrations." },
  AS: { name: "Assam",              slug: "assam",               psc: "APSC",
        desc: "APSC CCE, Assam Police constable/SI, TET teaching and Grade-III/IV board jobs make Guwahati one of the busiest recruitment hubs of the North-East." },
  BR: { name: "Bihar",              slug: "bihar",               psc: "BPSC",
        desc: "The most competitive state in India — BPSC 70th/71st CCE, Bihar Police CSBC, BSSC inter-level and teacher TRE exams see record-breaking applications every single month." },
  CT: { name: "Chhattisgarh",       slug: "chhattisgarh",        psc: "CGPSC",
        desc: "CGPSC State Service, Vyapam-style CG TGT/PRT teaching, CG Police and forest-guard openings drive recruitment across Raipur, Bilaspur and Bastar." },
  GA: { name: "Goa",                slug: "goa",                 psc: "Goa PSC",
        desc: "Small state, steady pipeline — Goa PSC advertises junior engineer, medical officer, police sub-inspector and multi-purpose technician posts through the year." },
  GJ: { name: "Gujarat",            slug: "gujarat",             psc: "GPSC",
        desc: "GPSC Class 1-2, GSSSB bin-sachivalay clerk, Gujarat Police PSI/constable and GSET form the core of one of India's most organised state recruitment ecosystems." },
  HR: { name: "Haryana",            slug: "haryana",             psc: "HPSC / HSSC",
        desc: "HPSC HCS and HSSC CET groups funnel candidates into police, patwari, clerk and engineer posts — Haryana's CET is now the gateway to most group-C/D jobs." },
  HP: { name: "Himachal Pradesh",   slug: "himachal-pradesh",    psc: "HPPSC",
        desc: "HPPSC HAS (state services), HP Police, TGT commission and JE posts recruit for India's most scenic duty stations from Shimla to Spiti." },
  JH: { name: "Jharkhand",          slug: "jharkhand",           psc: "JPSC",
        desc: "JPSC combined civil services plus JSSC CGL/inter-level, Jharkhand Police and TGT/PRT appointments serve Ranchi, Jamshedpur and the mineral belt." },
  JK: { name: "Jammu & Kashmir",    slug: "jammu-kashmir",       psc: "JKPSC / JKSSB",
        desc: "JKPSC KAS and JKSSB class-IV graduate-level notifications are the backbone of recruitment in the union territory, alongside JK Police and education department drives." },
  KA: { name: "Karnataka",          slug: "karnataka",           psc: "KPSC",
        desc: "KPSC KAS, FDA/SDA, Karnataka State Police and RRB's Bengaluru hub make the state a high-volume destination for central + state aspirants alike." },
  KL: { name: "Kerala",             slug: "kerala",              psc: "Kerala PSC",
        desc: "Kerala PSC runs the country's largest ranked-list system — LDC, university assistant, police constable, degree-level and plus-two level exams roll out monthly." },
  MP: { name: "Madhya Pradesh",     slug: "madhya-pradesh",      psc: "MPPSC",
        desc: "MPPSC State Service, MP Police SI/constable, VYAPAM (ESB) patwari-group exams and Samvida shala shikshak teaching posts dominate the heartland's job calendar." },
  MH: { name: "Maharashtra",        slug: "maharashtra",         psc: "MPSC",
        desc: "MPSC Rajyaseva, Maharashtra Police bharti, ZP bharti and Mumbai's central-board exams create India's biggest single-state recruitment volume." },
  MN: { name: "Manipur",            slug: "manipur",             psc: "MPSC Manipur",
        desc: "Manipur PSC combined competitive exams plus police and medical department drives serve Imphal valley and hill districts." },
  ML: { name: "Meghalaya",          slug: "meghalaya",           psc: "MPSC Meghalaya",
        desc: "Meghalaya PSC recruits for lower/senior selection grade posts, police services and education department roles across Shillong and the Garo hills." },
  MZ: { name: "Mizoram",            slug: "mizoram",             psc: "Mizoram PSC",
        desc: "Mizoram PSC conducts state service and departmental exams for Aizawl-headquartered departments plus district council vacancies." },
  NL: { name: "Nagaland",           slug: "nagaland",            psc: "NPSC",
        desc: "NPSC combined technical and non-technical services exams staff Kohima and Dimapur administration, police and education departments." },
  OR: { name: "Odisha",             slug: "odisha",              psc: "OPSC",
        desc: "OPSC OCS civil services, Odisha Police SI/constable, OTET teaching and OSSC combined posts make Bhubaneswar an evergreen exam destination." },
  PB: { name: "Punjab",             slug: "punjab",              psc: "PPSC",
        desc: "PPSC PCS, Punjab Police constable/intelligence-assistant and master-cadre teaching recruitments run on a tight, high-frequency schedule." },
  RJ: { name: "Rajasthan",          slug: "rajasthan",           psc: "RPSC",
        desc: "RPSC RAS, first-grade teacher (school lecturer), Rajasthan Police SI/constable and Patwari — the desert state's exam calendar never sleeps." },
  SK: { name: "Sikkim",             slug: "sikkim",              psc: "SPSC Sikkim",
        desc: "SPSC Sikkim state services and departmental posts offer some of India's least crowded government exams with generous per-post ratios." },
  TN: { name: "Tamil Nadu",         slug: "tamil-nadu",          psc: "TNPSC",
        desc: "TNPSC Group I/II/IV — the annual group-IV drive alone fills thousands of village-administration and clerical seats across Tamil Nadu." },
  TG: { name: "Telangana",          slug: "telangana",           psc: "TSPSC/TGPRC",
        desc: "TSPSC (now TGPRC) Group-1, TSLPRB police, gurukul TRT teaching and municipal jobs keep Hyderabad and district boards hiring year-round." },
  TR: { name: "Tripura",            slug: "tripura",             psc: "TPSC",
        desc: "TPSC joint/recruitment exams fill Agartala secretariat, police and school-service-commission roles at comfortable competition levels." },
  UP: { name: "Uttar Pradesh",      slug: "uttar-pradesh",       psc: "UPPSC",
        desc: "UPPSC PCS, UP Police (UPPRPB), UPSSSC PET-based group-C jobs, RO/ARO and Super TET — India's largest state also runs its largest recruitment machine." },
  UT: { name: "Uttarakhand",        slug: "uttarakhand",         psc: "UKPSC",
        desc: "UKPSC upper/middle PCS, UKSSSC group-C, Uttarakhand Police and LT-grade teaching serve Devbhoomi's hill and plain districts." },
  WB: { name: "West Bengal",        slug: "west-bengal",         psc: "WBPSC",
        desc: "WBPSC WBCS, clerkship, WB Police (WBP/WBPRI), SLST teaching and Kolkata Port jobs anchor the eastern region's biggest aspirant base." },
  AN: { name: "Andaman & Nicobar",  slug: "andaman-nicobar",     psc: "— (UPSC)",
        desc: "Island administration posts flow mostly through UPSC direct recruitment and A&N police/home-guard drives advertised by the island secretariat." },
  CH: { name: "Chandigarh",         slug: "chandigarh",          psc: "— (UPSC)",
        desc: "The city beautiful hires teachers, clerks and police through Chandigarh Administration and SSA notices aggregated under central listings." },
  DN: { name: "Dadra & Nagar Haveli and Daman & Diu", slug: "dadra-nagar-haveli", psc: "— (UPSC)",
        desc: "The merged UT recruits teachers, medical staff and revenue staff via administration walk-in and UPSC-advertised vacancies." },
  DD: { name: "Daman & Diu",        slug: "daman-diu",           psc: "— (UPSC)",
        desc: "Coastal UT administration posts — mostly teaching, health and multipurpose staff — surface through administration notifications." },
  DL: { name: "Delhi",              slug: "delhi",               psc: "DSSSB",
        desc: "DSSSB alone notifies tens of thousands of posts yearly — PRT/TGT/head-master teaching, Delhi Police auxiliary staff, nurses, clerks and AE/JE engineers." },
  LD: { name: "Lakshadweep",        slug: "lakshadweep",         psc: "— (UPSC)",
        desc: "The smallest UT staffs schools, health centres and administration through U.T. of Lakshadweep secretariat and UPSC direct recruitment." },
  PY: { name: "Puducherry",         slug: "puducherry",          psc: "PPPSC/Puducherry",
        desc: "Puducherry recruitment portal lists teacher, police constable, PHC staff and cooperative-department jobs for the UT and its enclaves." }
};

const CATEGORIES = [
  { icon: "🏛️", name: "UPSC",      desc: "IAS, IPS, CDS, NDA, CAPF, Civil Services", count: "42 live" },
  { icon: "📋", name: "SSC",       desc: "CGL, CHSL, MTS, GD Constable, JE", count: "68 live" },
  { icon: "🏦", name: "Banking",   desc: "IBPS PO/Clerk, SBI PO, RBI Grade B", count: "31 live" },
  { icon: "🚆", name: "Railways",  desc: "RRB NTPC, Group D, ALP, JE, Technician", count: "55 live" },
  { icon: "🛡️", name: "Defence",   desc: "Army, Navy, Air Force recruitment", count: "24 live" },
  { icon: "👮", name: "Police",    desc: "State SI, Constable, CAPF", count: "47 live" },
  { icon: "🎓", name: "Teaching",  desc: "CTET, State TET, KVS, NVS", count: "29 live" },
  { icon: "🏭", name: "PSU",       desc: "NTPC, ONGC, SAIL, ISRO, DRDO via GATE", count: "38 live" },
  { icon: "⚖️", name: "Judiciary", desc: "District Courts, High Court staff", count: "12 live" },
  { icon: "🗺️", name: "State PSC", desc: "All 28 State Civil Services exams", count: "73 live" }
];

const SAMPLE_JOBS = [
  { title: "SSC Combined Graduate Level (CGL) 2026 — 18,724 Posts", cat: "SSC", state: "All India", close: "2026-09-04", exam: "2026-11-14" },
  { title: "IBPS PO / Management Trainee XVI — 5,208 Posts",        cat: "Banking", state: "All India", close: "2026-08-28", exam: "2026-10-05" },
  { title: "RRB NTPC Graduate Level CEN 06/2026 — 11,558 Posts",    cat: "Railways", state: "All India", close: "2026-09-12", exam: "2026-12-20" },
  { title: "UPPSC PCS 2026 — 220 Posts",                            cat: "State PSC", state: "Uttar Pradesh", close: "2026-09-02", exam: "2026-10-26" },
  { title: "WBPSC Clerkship 2026 — 5,798 Posts",                    cat: "State PSC", state: "West Bengal", close: "2026-09-09", exam: "TBA" },
  { title: "SSC GD Constable 2026 — 39,481 Posts",                  cat: "SSC", state: "All India", close: "2026-09-30", exam: "2027-01-15" },
  { title: "Bihar BPSC 71st Combined Competitive — 1,299 Posts",    cat: "State PSC", state: "Bihar", close: "2026-08-27", exam: "2026-10-11" },
  { title: "TNPSC Group II Interview Posts — 3,643 Posts",          cat: "State PSC", state: "Tamil Nadu", close: "2026-09-19", exam: "2026-12-06" },
  { title: "KVS Teaching & Non-Teaching — 14,136 Posts",            cat: "Teaching", state: "All India", close: "2026-09-25", exam: "2026-12-13" }
];
